### ISSUE TITLE
Создать control для плоскости Эйзенхауэра

### ISSUE THREAD

**Issue by vkamiansky** [vkamiansky/fls-practice-dec-2018#16]
Control содержит четыре квадранта. Важность по вертикали, срочность по горизонтали. Пользователь может выбирать точку на этой плоскости.

**Comment by alexger97** [comment]
Каковы  детали реализации и какие ресурсы необходимы?

**Comment by vkamiansky** [comment]
Это должен быть контрол, который можно использовать в XAML-разметке UWP-приложения.

Вот статья с описанием создания контрола:
https://xamlbrewer.wordpress.com/2016/01/23/building-a-custom-uwp-control-with-xaml-and-the-composition-api/

Наш контрол тоже будет содержать фон с полем, расчерченным на 4 квадранта и градиентной заливкой. В нём будет точка, задающая выбор пользователя. 

Выполнение этого задания требует 1) разобраться с XAML, 2) разобраться с DependencyProperty

До субботы нужно постараться что-то сделать и набить как можно больше шишек, пытаясь создать этот контрол в изолированном проекте в отдельной папке, который будет тестироваться в очень простом UWP-приложении.
