### ISSUE TITLE
Создать и добавить в solution проект TaskList.Integration

### ISSUE THREAD

**Issue by vkamiansky** [vkamiansky/fls-practice-dec-2018#8]
Добавить сюда Composition Root, который получает экземпляр NavigationPage, который он подаст в NavigationService, регистрирует в Autofac все вью-модели, сервисы и репозитории и резолвит + возвращает реализацию IMainViewModel с полной композицией приложения.

**Comment by kirpichicus** [comment]
Добавлен TaskList.Integration  pull request
